### ISSUE TITLE
Search for tour files in subfolders

### ISSUE THREAD

**Issue by marcduiker** [pozil/codetour-watch#5]
I'm using CodeTour for a [repo](https://github.com/marcduiker/azure-functions-university) that also uses workspaces and nested folders for the CodeTour files.

The structure looks like this:

```
.tours/dotnet/http/.tours/
.tours/typescript/http/.tours/
...
```

Currently the action only looks for .tour files in one folder. Could that be changed so it looks in sub folders as well? Or, less ideal but workable, specify a list of folders instead?

**Comment by pozil** [comment]
Hi @marcduiker. This sounds like a reasonable ask :)
I've implemented this change in v1.3.0 with #6: we're now loading tours from subfolders.
